sudo: false
language: python

python:
  - "3.6"

install:
  - pip install coveralls -r requirements.txt
  - python setup.py -q install

script:
  - flake8
  - coverage run --source dotenv_config -m pytest

after_success:
  - coveralls

deploy:
  provider: pypi
  user: $PyPiLogin
  password: $PyPiPassword
  on:
    tags: true
